### ISSUE TITLE
source=iNaturalist observations unexpectedly not found by new monitor

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#35]
The monitor

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Elasmobranchii&traitSelector=&wktString=POLYGON%20%28%28130.4296875%20-24.846565348219745%2C%20130.4296875%20-2.460181181020993%2C%20162.421875%20-2.460181181020993%2C%20162.421875%20-24.846565348219745%2C%20130.4296875%20-24.846565348219745%29%29

contains 26 iNaturalist observations through source=gbif, but none through source=iNaturalist. I can imagine a scenario for this, but it seems very unlikely.

**Comment by jhpoelen** [comment]
Nice catch (no pun intended)!

Turns out that iNaturalist records don't mention the subclass `Elasmobranchii`, instead class `Chondrichthyes` is provided.  See the record snippet below. GBIF however, classified the shark species to be in class `Elasmobranchii` (see http://www.gbif.org/occurrence/1042818207). As Fresh Data uses the taxonomy provided by the sources, this explains why no `Elasmobranchii` records are found from inaturalist. Repeating the search with `Orectolobiformes` instead of `Elasmobranchii` should yield the expected results.

from inaturalist darwin core archive dd 2015-06-05

``` csv
id,occurrenceID,basisOfRecord,modified,institutionCode,collectionCode,datasetName,informationWithheld,catalogNumber,references,occurrenceRemarks,occurrenceDetails,recordedBy,establishmentMeans,associatedMedia,eventDate,eventTime,verbatimEventDate,verbatimLocality,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,identificationID,dateIdentified,identificationRemarks,taxonID,scientificName,taxonRank,kingdom,phylum,class,order,family,genus,rights,rightsHolder
1069749,http://www.inaturalist.org/observations/1069749,HumanObservation,2014-12-04T14:31:54Z,iNaturalist,Observations,iNaturalist research-grade observations,Coordinate uncertainty increased by 10000m to protect threatened taxon,1069749,http://www.inaturalist.org/observations/1069749,,http://www.inaturalist.org/observations/1069749,David R,wild,"http://lh6.ggpht.com/-2xbUk0igzPM/VGMePLEy74I/AAAAAAAAiL0/OSe9Sv7y-TY/s512/PA310106.jpg, https://picasaweb.google.com/104623964081378888743/20141101LadyElliottIsland2#6080737167900077954",2014-10-31T14:27:00-07:00,21:27:00Z,"October 31, 2014 11:27","Lady Elliott Island, AU",-24.0933424734,152.7966124315,10350,1911124,2014-11-12T08:59:24Z,"",52300,Stegostoma fasciatum,species,Animalia,Chordata,Chondrichthyes,Orectolobiformes,Stegostomatidae,Stegostoma,"Copyright David R, licensed under a Creative Commons cc_by_nc_name license: http://creativecommons.org/licenses/by-nc/3.0/",David R
```

**Comment by jhammock** [comment]
Of course; so often it boils down to names...
