### ISSUE TITLE
error message, one particular query, previously functioning

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#64]
[not ok. Received a [0] status with text [] in response to 

[http://api.effechecka.org/occurrences?limit=20&taxonSelector=Fratercula%20arctica%2CArdenna%20gravis%2CPuffinus%20puffinus%2CMorus%20bassanus%2CLagenorhynchus%20acutus%2CHalichoerus%20grypus%2CCystophora%20cristata%2CEubalaena%20glacialis%2CHyperoodon%20ampullatus%2CLagenorhynchus%20albirostris%2CAlca%20torda&wktString=GEOMETRYCOLLECTION(POLYGON%20((-180%2032.71%2C%20-180%2066.56%2C%20-135.703125%2061.938950426660604%2C%20-121.640625%2052.908902047770255%2C%20-117.7734375%2032.71%2C%20-180%2032.71))%2CPOLYGON%20((116.71874999999999%2032.71%2C%20130.78125%2047.517200697839414%2C%20137.109375%2063.548552232036414%2C%20150.46875%2062.59334083012024%2C%20165.9375%2063.860035895395306%2C%20180%2066.56%2C%20180%2032.71%2C%20116.71874999999999%2032.71)))]] ?

This query has previously returned results. It was cached, but could have been un-cached since as inactive. I wonder if perhaps it's too long, or violates some constraint recently added for performance considerations...

**Comment by jhpoelen** [comment]
@jhammock copying your arguments into a checklist generator seems to produce some results (see [checklist results](http://www.effechecka.org/?limit=20&taxonSelector=Fratercula%20arctica%2CArdenna%20gravis%2CPuffinus%20puffinus%2CMorus%20bassanus%2CLagenorhynchus%20acutus%2CHalichoerus%20grypus%2CCystophora%20cristata%2CEubalaena%20glacialis%2CHyperoodon%20ampullatus%2CLagenorhynchus%20albirostris%2CAlca%20torda&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-180%2032.71%2C%20-180%2066.56%2C%20-135.703125%2061.938950426660604%2C%20-121.640625%2052.908902047770255%2C%20-117.7734375%2032.71%2C%20-180%2032.71%29%29%2CPOLYGON%20%28%28116.71874999999999%2032.71%2C%20130.78125%2047.517200697839414%2C%20137.109375%2063.548552232036414%2C%20150.46875%2062.59334083012024%2C%20165.9375%2063.860035895395306%2C%20180%2066.56%2C%20180%2032.71%2C%20116.71874999999999%2032.71%29%29%29)). 

However, server logs suggest that the arguments failed to parse:

```
[ERROR] [03/24/2017 13:54:43.594] [effechecka-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(effechecka)] Error during processing of request HttpRequest(HttpMethod(GET),http://localhost:8888/occurrences?taxonSelector=Fratercula%20arctica%2CArdenna%20gravis%2CPuffinus%20puffinus%2CMorus%20bassanus%2CLagenorhynchus%20acutus%2CHalichoerus%20grypus%2CCystophora%20cristata%2CEubalaena%20glacialis%2CHyperoodon%20ampullatus%2CLagenorhynchus%20albirostris%2CAlca%20torda&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-180%2032.71%2C%20-180%2066.56%2C%20-135.703125%2061.938950426660604%2C%20-121.640625%2052.908902047770255%2C%20-117.7734375%2032.71%2C%20-180%2032.71%29%29%2CPOLYGON%20%28%28116.71874999999999%2032.71%2C%20130.78125%2047.517200697839414%2C%20137.109375%2063.548552232036414%2C%20150.46875%2062.59334083012024%2C%20165.9375%2063.860035895395306%2C%20180%2066.56%2C%20180%2032.71%2C%20116.71874999999999%2032.71%29%29%29,List(Host: localhost:8888, Connection: close, User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.1144, Accept: text/html, application/xhtml+xml, application/xml;q=0.9, image/webp, */*;q=0.8, Accept-Language: en-US, en;q=0.8, Upgrade-Insecure-Requests: 1, Accept-Encoding: gzip, Timeout-Access: <function1>),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.0))
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at spray.json.BasicFormats$StringJsonFormat$.write(BasicFormats.scala:121)
	at spray.json.BasicFormats$StringJsonFormat$.write(BasicFormats.scala:119)
	at spray.json.PimpedAny.toJson(package.scala:39)
	at spray.json.StandardFormats$OptionFormat.write(StandardFormats.scala:34)
	at spray.json.StandardFormats$OptionFormat.write(StandardFormats.scala:32)
	at spray.json.ProductFormats$class.productElement2Field(ProductFormats.scala:46)
	at effechecka.WebApi$.productElement2Field(WebApi.scala:339)
	at spray.json.ProductFormatsInstances$$anon$3.write(ProductFormatsInstances.scala:73)
```

As far as I can tell, this issue is unrelated to https://github.com/jhpoelen/effechecka/issues/49 , especially since I was able to make multiple requests for (new and old) freshdata occurrences through http://gimmefreshdata.github.io . 

Some time is needed to further troubleshoot this issue.

**Comment by jhammock** [comment]
I'm not sure this error is meaningfully reproduceable. An almost-identical query is now behaving itself perfectly and I haven't seen this behavior anywhere else. I wonder if this issue should be closed
