### ISSUE TITLE
API support for uuid parameter

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#71]
Should the occurrences and monitoredOccurrences APIs support fetching of existing monitor results by the monitor uuid? This is nice functionality for use cases requiring compactness, eg: emailing searchers their queries. 

BUT it may cause confusion for searchers in possession of a uuid that is not known to the system (most likely, a monitor that has expired). (Jen has little sympathy for searchers who don't make contact with admin, provide metadata, and  get their monitors archived in the monitors v2 index, so this doesn't bother her.)

**Comment by jhpoelen** [comment]
UUID queries have been re-introduced due to popular demand! Please confirm that functionality is working as expected by closing this issue. 

Example: http://api.effechecka.org/checklist?uuid=fde214ae-b44c-53df-8838-14d55bba8d4a

Only checklist/occurrences that have been previously processed can be requested by uuid. On requesting checklist/occurrences with a unknown uuid, a "bad request" will be returned.

**Comment by jhammock** [comment]
This is working. Interestingly, Google offered to translate the results of http://api.effechecka.org/occurrences?uuid=93ac6418-e1a7-5697-a117-fd8ef9453826 

from Welsh.

**Comment by jhpoelen** [comment]
Cool! Can you attach a screen shot of the translation? Who knew that Welsh has similar linguistic features as occurrences lists... perhaps an unexpected avenue of research from our prototype...

**Comment by jhammock** [comment]
![screen shot 2017-07-11 at 1 40 30 pm](https://user-images.githubusercontent.com/3026567/28081844-aa1fbd54-663e-11e7-9cce-e5d08e94e306.png)
